import { $ } from "bun";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import path from "path";

async function buildStyles() {
    console.log("🚀 Building Tailwind styles...");

    const inputCss = "src/mainview/index.css";
    const outputCss = "src/mainview/index.compiled.css";
    const outputTs = "src/mainview/styles/tailwind.css.ts";

    try {
        // v4 CLI is available through child_process or bun's $
        // We'll use npx to ensure it's the right version
        await $`npx -y @tailwindcss/cli@latest -i ${inputCss} -o ${outputCss}`;

        if (!existsSync(outputCss)) {
            throw new Error("Failed to generate compiled CSS");
        }

        const cssContent = readFileSync(outputCss, "utf8");
        
        // Escape backticks and dollar signs for template literal
        const escapedCss = cssContent
            .replace(/\\/g, "\\\\") // Escape backslashes
            .replace(/`/g, "\\`")   // Escape backticks
            .replace(/\$/g, "\\$");  // Escape dollar signs

        const tsContent = `import { css } from "lit";

/**
 * AUTO-GENERATED TAILWIND STYLES
 * Do not edit this file directly. Run "bun run build:styles" instead.
 */
export const tailwindStyles = css\`
${escapedCss}
\`;

export default tailwindStyles;
`;

        const dir = path.dirname(outputTs);
        if (!existsSync(dir)) {
            mkdirSync(dir, { recursive: true });
        }

        writeFileSync(outputTs, tsContent);
        console.log("✅ Styles built successfully to " + outputTs);
    } catch (error) {
        console.error("❌ Error building styles:", error);
        process.exit(1);
    }
}

buildStyles();
